# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-15 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('Name', models.CharField(max_length=120)),
                ('Subname', models.CharField(max_length=120)),
                ('Address', models.CharField(max_length=120)),
                ('Phone_Number', models.CharField(max_length=120)),
                ('E_mail', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=120)),
                ('Repeat_password', models.CharField(max_length=120)),
            ],
        ),
    ]
